apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: asset.events
  namespace: homestarter-ns
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 86400000  # 24 hours
    compression.type: lz4
    min.insync.replicas: 1
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: housing.events
  namespace: homestarter-ns
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 86400000  # 24 hours
    compression.type: lz4
    min.insync.replicas: 1
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: dlq.events
  namespace: homestarter-ns
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 604800000  # 7 days
    compression.type: lz4
    min.insync.replicas: 1
